server:
  port: "8080"
  # 外部访问地址，用于生成分享给客户端的接入URL
  external_url: "http://150.109.14.216:8088"
victorialogs:
  url: "http://localhost:9428"
database:
  path: "vsentry.db"
jwt:
  secret: vsentry_secret_fetajndkmslaihyr